---
title: "Compare tests with multiple responses"
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r format(Sys.time(), '%a %b %d %X %Y')`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---

<!--- 
# run analysis
cd /Users/gabrielhoffman/workspace/repos/misc_vp

cd /sc/arion/projects/CommonMind/hoffman/misc_vp
cd /hpc/users/hoffmg01/work/misc_vp/
R

system("ml git; git pull"); rmarkdown::render("compare_multivariate_tests.Rmd", output_dir='./', intermediates_dir='./')

https://hoffmg01.hpc.mssm.edu/misc_vp/compare_multivariate_tests.html

# LS_empirical_Dev.R

--->

```{r load.knitr, echo=FALSE}
options(xtable.type="html")

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=TRUE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE,
  dev = c("png", "pdf"), 
  fig.width=7, fig.height=7)

options(markdown.HTML.stylesheet = 'css/custom.css')
```

```{r define.function}
#' Meta-analysis using Sidak correction
#'
#' Meta-analysis using Sidak correction evaluating the minimum 
#' p-value correcting for the number of tests.
#'
#' @param pValues array of p-values 
#' @param ntests number of tests to correct for.  If missing, just counts number of p-values
#' @param na.rm: a logical indicating whether missing values should be removed.
#'
#' @details
#' The Sidak method corrects a p-value based on the number of tests performed.  
#' Given a p-value p and n tests, the Sidak corrected p-value is 1-(1-min(p))^n 
#'
#' @examples
#' p = runif(10)
#'
#' # assume independent tests
#' meta_sidak( p )
#' 
#' # assume correlation structure leads to 5.4 "effective tests"
#' meta_sidak( p )
#'
meta_sidak = function(pValues, ntests, na.rm=FALSE){

	if( min(pValues) < 0 || max(pValues) > 1){
		stop("p-values must be in the range [0,1]")
	}

	if( missing(ntests) ){
		# get the number of tests
		# if na.rm==TRUE, get the number of tests without NA values
		ntests = ifelse( na.rm, sum(!is.na(pValues)), length(pValues))
	}

	# return corrected p-value
	1 - (1 - min(pValues, na.rm=na.rm))^ntests
}

meta_fisher = function(pValues){
	stat = -2 * sum(log(pValues))
	k = length(pValues)
	pchisq(stat, 2*k, lower.tail=FALSE)
}
```

```{r simulations, echo=TRUE}
library(mvtnorm)
library(ggplot2)
library(poolr)
library(remaCor)
library(cowplot)
library(Matrix)
library(CovTools)
library(parallel)
library(metafor)
 
n = 100
p = 15
m = 1
rho = .5
# Sigma = as.matrix(bdiag(matrix(rho, p/2, p/2), matrix(rho, p/2, p/2)))
Sigma = matrix(rho, p, p)
diag(Sigma) = 1
 
n_tests = 1000

res = mclapply( 1:n_tests, function(i){

	RhpcBLASctl::omp_set_num_threads(1) 

	X = matrix(rnorm(n*m), ncol=m)

	isDE = i <= n_tests/4

	if( isDE ){
		beta = matrix(.6, m, p)
	}else{
		beta = matrix(0, m, p)
	}

	Y = X %*% beta + mvtnorm::rmvnorm(n, sigma = Sigma)*5

	# Multivariate regression
	# lm.anova
	fit = lm(Y ~ X)
	p.lm_anova = anova(fit)['X', 'Pr(>F)']

	# Model each response separately
	# Then take min p-value
	fitList = apply(Y, 2, function(y) lm(y~X))
	p.separate = sapply(fitList, function(x) anova(x)['X', 'Pr(>F)'])

	# combine p-values with sidak correction
	p.meta_sidak = meta_sidak( p.separate, length(p.separate) )

	p.fisher = meta_fisher(p.separate)

	# Meta-analysis
	df = lapply(coef(summary(fit)), function(x) data.frame(beta = x["X", 1], se = x["X", 2]))
	df = do.call(rbind, df)

	P = residuals(fit)
	# lambda = corpcor::estimate.lambda(P, verbose=FALSE)
	# lambda = CovEst.2010RBLW(scale(P))$rho
	lambda = decorrelate::eclairs(P, compute="cor")$lambda
	# lambda = ShrinkCovMat::shrinkcovmat.identity(t(scale(P)))$lambdahat

	S = (1-lambda)*cor(P) + lambda*diag(diag(cor(P)), ncol(P))

	# True correlction
	# S = Sigma

	nu = fit$df.residual[1]

	p.LS.lambda = with(df, LS(beta, se, S))$p
	p.LS.empirical.lambda.remaCor = with(df, remaCor::LS.empirical(beta, se, S, nu[1], n.mc.samples=1e3))$p
	# p.LS.empirical.lambda = with(df, LS.empirical(beta, se, S, nu[1], n.mc.samples=1e3))$p
	p.RE2C.lambda = with(df, RE2C(beta, se, S))$RE2Cp

	p.LS = with(df, LS(beta, se, cor(P)))$p
	# p.LS.empirical = with(df, LS.empirical(beta, se, cor(P), nu[1], n.mc.samples=1e3))$p
	p.RE2C= with(df, RE2C(beta, se, cor(P)))$RE2Cp

	p.hotelling = with(df, hotelling(beta, diag(se) %*% cor(P) %*% diag(se), n))$p.value

	# fixed effects test
	fema = with(df, rma(yi=beta, sei=se, method="EE"))

	data.frame(	i 			= i,
				isDE		= isDE, 
				beta = beta[1],
				lambda,
				p.fisher = p.fisher,
				p.lm_anova 	= p.lm_anova,
				# p.separate 	= min(p.separate), 
				p.meta_sidak = p.meta_sidak,
				p.LS 		= p.LS,
				# p.LS.empirical = p.LS.empirical,
				p.RE2C = p.RE2C,
				p.LS.lambda = p.LS.lambda,
				# p.LS.empirical.lambda = p.LS.empirical.lambda,
				p.LS.empirical.lambda.remaCor = p.LS.empirical.lambda.remaCor,
				p.RE2C.lambda = p.RE2C.lambda,
				p.hotelling = p.hotelling)#,
				# p.fixed = fema$pval )
}, mc.cores=24)
res = do.call(rbind, res)
```

```{r aupr, fig.width=12, fig.height=6, cache=FALSE}
library(PRROC)
library(ggplot2)
library(cowplot)

df_aupr = lapply( colnames(res)[-c(1:4)], function(method){

	pr = pr.curve( -log10(res[[method]][res$isDE]), -log10(res[[method]][!res$isDE]), curve=TRUE )
	
	data.frame(method = method, AUPR = pr$auc.integral)
})
df_aupr = do.call(rbind, df_aupr)

fig1 = ggplot(df_aupr, aes(method, AUPR, fill=method)) + 
	geom_bar(stat="identity") + 
	theme_bw(14) + 
	theme(aspect.ratio=1, legend.position="none") + 
	coord_flip() + 
	ggtitle("Performance of methods for multiple responses") + 
	geom_hline(yintercept=1/4, linetype="dashed", color="grey30")

df_fpr = lapply( colnames(res)[-c(1:4)], function(method){

	fpr = sum(res[[method]][!res$isDE] < 0.05) / length(res[[method]][!res$isDE])
	
	data.frame(method = method, FPR = fpr)
})
df_fpr = do.call(rbind, df_fpr)

fig2 = ggplot(df_fpr, aes(method, FPR, fill=method)) + 
	geom_bar(stat="identity") + 
	theme_bw(14) + 
	theme(aspect.ratio=1, legend.position="none") + 
	coord_flip() + 
	ggtitle("Performance of methods for multiple responses") + 
	geom_hline(yintercept=0.05, linetype="dashed", color="grey30")

plot_grid(fig1, fig2)
```












