---
title: "COVID and variancePartition"
subtitle: ''
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---


<!---

cd /hpc/users/hoffmg01/work/misc_vp
# rm -rf molec_profiling_cache/
ml git pandoc 
git pull
R

system("git pull")


rmarkdown::render("covid_vp.Rmd")



--->

```{r setup, include=FALSE}
suppressPackageStartupMessages({
library(ggplot2)
library(data.table)
library(cowplot)
library(kableExtra)
library(knitr)
library(compositions)
library(BiocParallel)

library(limma)
library(edgeR)
library(variancePartition)

})

knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE)
```

# Variance partitioning
Compute variance partitioning for cell fractions (log ratios) for the whole dataset and then each tissue
```{r}

info = fread("/sc/arion/projects/CommonMind/roussp01a/COVID_SC/FrozenBrain/results/freq_celltype.csv")
info$covid = factor(info$covid)

table(info$pid)
table(info$subject)
table(info$clinical)
table(info$tissue)
table(info$covid)

# use observed cell type frations
# CT.quant = t(info[,1:15])

# use centered log ratios
pseudoFrac = 1e-4
CT.quant = t(clr(info[,1:15] + pseudoFrac))

# form = ~ (1|pid) + (1|subject) + (1|covid) + (1|tissue)
form = ~ (1|pid) + (1|subject) + (1|covid) + (covid|tissue)

vp = fitExtractVarPartModel( CT.quant, form, info)  

plotPercentBars(vp)
``` 

```{r per.tissue, fig.width=12}
form = ~ (1|pid) + (1|subject) + (1|covid)
vpList = lapply( unique(info$tissue), function(Tissue){

  idx = which(info$tissue == Tissue)

  fitExtractVarPartModel( CT.quant[,idx], form, info[idx,]) 
})
names(vpList) = unique(info$tissue)

figList = lapply( names(vpList), function(id){
  plotPercentBars( vpList[[id]] ) + ggtitle(id) + theme(legend.position="bottom")
  }) 

plot_grid(plotlist = figList, ncol=3)
```






```{r read.gene.expression, eval=FALSE}
geneExpr = fread('/sc/arion/projects/CommonMind/roussp01a/COVID_SC/FrozenBrain/results/gene_expression_v10k.csv')
metadata = fread('/sc/arion/projects/CommonMind/roussp01a/COVID_SC/FrozenBrain/results/metadata.csv')
```









