---
title: "Compare dreamlet version"
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r format(Sys.time(), '%a %b %d %X %Y')`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---

<!--- 
# run analysis
cd /hpc/users/hoffmg01/work/misc_vp/dreamlet_debug_milos
R

system("ml git; git pull"); rmarkdown::render("compare.Rmd")


https://hoffmg01.hpc.mssm.edu/misc_vp/compare_multivariate_tests.html

--->

```{r load.knitr, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(scattermore)
library(dreamlet)

options(xtable.type="html")

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=TRUE,
  error = FALSE,
  tidy = FALSE,
  cache = FALSE,
  dev = c("png", "pdf"), 
  fig.width=7, fig.height=7)

options(markdown.HTML.stylesheet = 'css/custom.css')
```

```{r example, eval=FALSE}
res.proc1 = readRDS("/sc/arion/scratch/hoffmg01/milos/old/cerad_resproc_subtype_dx.RDS")
res.proc2 = readRDS("/sc/arion/scratch/hoffmg01/milos/v131/cerad_resproc_subtype_dx.RDS")

pb1 = readRDS("/sc/arion/scratch/hoffmg01/milos/old/pb.RDS")
pb2 = readRDS("/sc/arion/scratch/hoffmg01/milos/v131/pb.RDS")

CT = 'EPIT_5_2'
gene = "CCN2"
a = res.proc1[[CT]][gene,]
b = res.proc2[[CT]][gene,]


# plot(t(a$E), t(b$E))

# examine top hit
data = merge(t(a$E), data.frame(colData(pb1)), by="row.names")
boxplot(CCN2 ~ cerad_4_12_24, data, main=gene)

# examine weights
# the weights from the old version are _extreme_
plot(t(a$weights), t(b$weights), xlab="old", ylab="v131", main=paste("weights: ", CT, gene))
```



# Voom 

```{r voom, fig.height=40, eval=FALSE}}
fit1 = lm.wfit( a$design, t(a$E), c(a$weights))
fit2 = lm.wfit( b$design, t(b$E), c(b$weights))

cbind(fit1$coefficients, fit2$coefficients)

plotVoom(res.proc1) + ggtitle("old")

plotVoom(res.proc2) + ggtitle("v131")
```




# logFC 

```{r logFC, fig.height=40}
file = "/sc/arion/scratch/hoffmg01/milos/old/cerad_subtype_dx.csv"
tab1 = read.table(file, row.names=1, header=TRUE, sep=',') %>%
			as_tibble

file = "/sc/arion/scratch/hoffmg01/milos/v131/cerad_subtype_dx.csv"
tab2 = read.table(file, row.names=1, header=TRUE, sep=',') %>%
			as_tibble

df = inner_join(tab1, tab2, by=c("assay", 'ID'))

# logFC
ggplot(df, aes(logFC.x, logFC.y, color=ifelse(adj.P.Val.x < 0.05, "red", "black"))) +
		geom_scattermore(pointsize=3) +
		facet_wrap(~assay, ncol=3, scales="free") +
		theme_bw() +
		scale_color_manual(values=c("red" = "red", "black" = "black")) +
		theme(aspect.ratio=1, legend.position="none") +
		geom_abline(color="red") +
		xlab("logFC (old)") +
		ylab("logFC (v131)") 
```



# t-statistic 
```{r t, fig.height=40}
# t-stat
ggplot(df, aes(t.x, t.y, color=ifelse(adj.P.Val.x < 0.05, "red", "black"))) +
		geom_scattermore(pointsize=3) +
		facet_wrap(~assay, ncol=3, scales="free") +
		theme_bw() +
		scale_color_manual(values=c("red" = "red", "black" = "black")) +
		theme(aspect.ratio=1, legend.position="none") +
		geom_abline(color="red") +
		xlab("t (old)") +
		ylab("t (v131)")

sum(df$adj.P.Val.x < 0.05)
sum(df$adj.P.Val.y < 0.05)


cor(df$t.x, df$t.y)

df %>%
	head %>%
	data.frame
```



