---
title: "Somatic rate differential expression analysis"
subtitle: 'dreamlet analysis of PsychAD'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: true
---


<!--- 

cd /hpc/users/hoffmg01/work/misc_vp/somatic_rate
ml git pandoc
R


system("git pull")
rmarkdown::render("somatic_rate_de.Rmd")

\cp -f /hpc/users/hoffmg01/work/misc_vp/somatic_rate/somatic_rate_de.html ~/www/


rsync -avzP minerva:"/hpc/users/hoffmg01/work/misc_vp/somatic_rate/somatic_rate_de_files /hpc/users/hoffmg01/work/misc_vp/somatic_rate/somatic_rate_de.html" .




--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = TRUE)
```


# Differential expression based on somatic rate
```{r load.packages, cache=FALSE}
suppressPackageStartupMessages({
library(tidyverse)
library(lme4)
library(variancePartition)
library(ggplot2)
library(dreamlet)
library(zenith)
RhpcBLASctl::omp_set_num_threads(4)
})
```

```{r load.rate}
# Load estimated somatic rate
df = readRDS("/hpc/users/hoffmg01/work/somatic_rate/PsychAD_SMrate_poolID.rds") %>%
      as_tibble

# Evaluate correlation across technical replicates
res = lapply( unique(df$CellType), function(CT){
  data = df %>%
    filter(CellType == CT)

  fit = lmer( SomaticRate ~ (1|SubID), data )  
  vp = calcVarPart(fit)

  data.frame(CellType = CT, R2_SubID = vp[[1]])
}) %>%
  bind_rows

res %>%
  ggplot(aes(R2_SubID, CellType)) +
    geom_bar(stat="identity") + 
    theme_classic() + 
    theme(aspect.ratio=1) +
    scale_x_continuous(lim=c(0,1), expand=c(0,0)) +
    xlab("Intra class correlation")
```


# Differential expression
```{r processAssays, cache.lazy=FALSE}
# read Pseudobulk
file = "/sc/arion/projects/psychAD/NPS-AD/freeze2_rc/pseudobulk/FULL_2024-02-01_18_49_PB_SubID_class.RDS"
pb = readRDS(file)

# merge with SomaticRate for each SubID and cell class
metadata(pb)$aggr_means = metadata(pb)$aggr_means %>%
  left_join(df %>% 
    dplyr::rename(class = CellType) %>%
    select(class, SubID, SomaticRate, Age) %>%
    group_by(class, SubID) %>%
    summarize(SomaticRate = mean(SomaticRate)) %>%
    distinct,
    by = c("class", "SubID"))

metadata(pb)$aggr_means$SomaticRate[1:3]

# Account for AD, SCZ, PD, Dementia
# X = with(colData(pb), data.frame(c11x,c10x,c33x,r09x))

# voom-style normalization
formula = ~ scale(Age) + Sex + scale(PMI) + log(n_genes) + percent_mito + mito_genes + ribo_genes + mito_ribo 

res.proc <- processAssays(pb, formula)
rm(pb)
```



# run dreamlet
```{r dreamlet, cache.lazy=FALSE}
fitList = list()

form = update(formula, ~ . + SomaticRate + c11x)
fitList[["SomaticRate"]] = dreamlet( res.proc, form)

form = update(formula, ~ . + SomaticRate*c11x)
fitList[["SomaticRate:Dx"]] = dreamlet( res.proc, form)

form = update(formula, ~ . + SomaticRate*scale(Age))
fitList[["SomaticRate:Age"]] = dreamlet( res.proc, form)
```





```{r results, cache=FALSE}
tab1 = topTable(fitList[["SomaticRate"]], 
  "SomaticRate", number=Inf) %>%
  as_tibble %>%
  mutate(test = "SomaticRate")

tab2 = topTable(fitList[["SomaticRate:Dx"]], 
  "SomaticRate:c11x.L", number=Inf) %>%
  as_tibble %>%
  mutate(test = "SomaticRate:Dx")

tab3 = topTable(fitList[["SomaticRate:Age"]], 
  "scale(Age):SomaticRate", number=Inf) %>%
  as_tibble %>%
  mutate(test = "SomaticRate:Age")

bind_rows(tab1, tab2, tab3) %>%
  group_by(test, assay) %>%
  summarize(nFDR = sum(adj.P.Val < 0.05)) %>%
  ggplot(aes(nFDR, assay)) +
    geom_bar(stat="identity") +
    theme_classic() +
    theme(aspect.ratio=1, legend.position="none") +
    scale_x_continuous(limits=c(0, NA)) +
    facet_wrap(~test)
```

```{r zenith}
go.gs <- get_GeneOntology(c("BP", "MF", "CC"), to = "SYMBOL")

res.zen1 = zenith_gsa(fitList[["SomaticRate"]], go.gs, "SomaticRate") %>%
  as_tibble %>%
  mutate(test = "SomaticRate")

res.zen2 = zenith_gsa(fitList[["SomaticRate:Dx"]], go.gs, "SomaticRate:c11x.L") %>%
  as_tibble %>%
  mutate(test = "SomaticRate:Dx")

res.zen3 = zenith_gsa(fitList[["SomaticRate:Age"]], go.gs, "scale(Age):SomaticRate") %>%
  as_tibble %>%
  mutate(test = "SomaticRate:Age")
```

```{r plot.zenith, fig.height=12, fig.width=10, cache=FALSE}
res.zen1 %>%
  filter(NGenes < 2000) %>%
  plotZenithResults(10, 1) + ggtitle("SomaticRate")

res.zen2 %>%
  filter(NGenes < 2000) %>%
  plotZenithResults(10, 1) + ggtitle("SomaticRate:Dx")

res.zen3 %>%
  filter(NGenes < 2000) %>%
  plotZenithResults(10, 1) + ggtitle("SomaticRate:Age")
```



<!--- 
saveRDS( tab, file="somatic_rate_DE.RDS")
saveRDS( res_zenith, file="somatic_rate_DE_genesets.RDS")

--->


